### ISSUE TITLE
关于react框架渲染指定路由的问题

### ISSUE THREAD

**Issue by javaswing** [yuntian001/midway-vite-view#1]
你好，项目中在`midway v3`框架，使用了该view渲染且为`react`。目前在使用中发需要渲染指定的路由。在翻看源码时发在下如下地址指定的渲染的`URL`:
https://github.com/yuntian001/midway-vite-view/blob/055add78ea87ee35cabc01fc6d07260e326f7854/src/lib/view.ts#L97
写出了如下代码：

> 系统中已经有如下页面及路由：
> <img width="230" alt="image" src="https://user-images.githubusercontent.com/7713463/168268843-56ef765f-aacd-4f24-a1ac-ccf652c6e0dc.png">

```ts
 //服务端渲染
    const html = await this.ctx.render('index.html', {
      entry: 'src/entry-server.jsx',
      ctx: { originalUrl: '/content' },
      assign: { title: 'vite midway' }, //html中{{title}}的会被替换为vite midway
    });
```
发现会闪一下指定路页面内容，由然后重写向了home页面，请麻烦作者告知正确的使用方法。 @yuntian001

**Comment by yuntian001** [comment]
你访问的路由是否和需要渲染的路由一致，当前应用的你访问的路由。@javaswing

**Comment by yuntian001** [comment]
好的，本人主要使用在vue3中，react是直接拿的vite官方demo做的示例，欢迎提供react相关的PR。
现在发现的是example中的react 降级为客户端渲染时会直接报错，主要是react demo的构建问题，如果您有时间可以完善下react相关。非常感谢。
